name: "boats"

profile: 'boats'

models:
  boats:
    warehouse:
      +enabled: true
      +materialized: table
      # +schema: dbt_hnguyen
    analytics:
      +enabled: true
      +materialized: table
      # +schema: prod_secondhandBoats

vars:
  surrogate_key_treat_nulls_as_empty_strings: true #turn on legacy behaviour
    