version: "3.1"
services:
  metabase:
    image: metabase/metabase:latest
    volumes:
      - ./metabase-data:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db 
    ports:
      - 3001:3001
    restart: always